image: mcr.microsoft.com/dotnet/sdk:6.0
variables:
  RELEASE_DIRECTORY: 'bin/*'
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'MaeveFramework/'
cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push
before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
build:
  stage: build
  script:
    - 'dotnet build --no-restore --configuration Release'
  artifacts:
    paths:
      - "$SOURCE_CODE_PATH$RELEASE_DIRECTORY/*.nupkg"
      - "$SOURCE_CODE_PATH$RELEASE_DIRECTORY/*/MaeveFramework.dll"
    expire_in: 1 week
# tests:
#   stage: test
#   script:
#     - 'dotnet test --no-restore --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
#   artifacts:
#     when: always
#     paths:
#       - ./**/*test-result.xml
#     reports:
#       junit:
#         - ./**/*test-result.xml
# include:
#   - template: Security/Dependency-Scanning.gitlab-ci.yml
#   - template: Security/License-Scanning.gitlab-ci.yml
#   - template: Security/SAST.gitlab-ci.yml